{% set name = "libgsf" %}
{% set version = "1.14.48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnome.org/pub/GNOME/sources/{{ name }}/{{ ".".join(version.split(".")[:2]) }}/{{ name }}-{{ version }}.tar.xz
  sha256: ff86d7f1d46dd0ebefb7bd830a74a41db64362b987bf8853fff6ab4c1132b837

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libgsf", max_pin="x.x") }}

requirements:
  build:
    - perl *
    - perl-xml-parser
    - pkg-config
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
  host:
    - glib
    - libxml2
    - zlib
    - bzip2
    - pcre
  run:
    - glib
    - libxml2
    - zlib
    - bzip2

test:
  commands:
    - gsf --help
    - gsf --version

about:
  home: https://github.com/GNOME/libgsf
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: An extensible I/O abstraction library for dealing with structured file formats

extra:
  recipe-maintainers:
    - sebastian-luna-valero
