{% set name = "libgsf" %}
{% set version = "1.14.52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnome.org/pub/GNOME/sources/{{ name }}/{{ ".".join(version.split(".")[:2]) }}/{{ name }}-{{ version }}.tar.xz
  sha256: 9181c914b9fac0e05d6bcaa34c7b552fe5fc0961d3c9f8c01ccc381fb084bcf0
  patches:
    # https://github.com/GNOME/libgsf/commit/0d0cc90e667faafa70481ac1f79c4068093910e3
    - libxml2212.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libgsf", max_pin="x.x") }}

requirements:
  build:
    - perl *
    - perl-xml-parser
    - pkg-config
    - gnuconfig  # [unix]
    - make  # [unix]
    - {{ compiler('c') }}
  host:
    - glib
    - libxml2
    - zlib
    - bzip2
    - pcre
  run:
    - glib
    - libxml2
    - zlib
    - bzip2

test:
  commands:
    - gsf --help
    - gsf --version

about:
  home: https://github.com/GNOME/libgsf
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: An extensible I/O abstraction library for dealing with structured file formats

extra:
  recipe-maintainers:
    - sebastian-luna-valero
