{% set name = "libgsf" %}
{% set version = "1.14.53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnome.org/pub/GNOME/sources/{{ name }}/{{ ".".join(version.split(".")[:2]) }}/{{ name }}-{{ version }}.tar.xz
  sha256: 0eb59a86e0c50f97ac9cfe4d8cc1969f623f2ae8c5296f2414571ff0a9e8bcba

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libgsf", max_pin="x.x") }}

requirements:
  build:
    - perl *
    - perl-xml-parser
    - pkg-config
    - gnuconfig  # [unix]
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - glib
    - libxml2
    - zlib
    - bzip2
    - pcre

test:
  commands:
    - gsf --help
    - gsf --version

about:
  home: https://github.com/GNOME/libgsf
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: An extensible I/O abstraction library for dealing with structured file formats

extra:
  recipe-maintainers:
    - sebastian-luna-valero
